[package]
name = "amethyst_playground"
version = "0.1.0"
authors = ["Allan Clements"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
